### ISSUE TITLE
Conflicts with Kaoses Tweaks

### ISSUE THREAD

**Issue by EvilTactician** [Shadow32055/Bannerlord.BetterAttributes#1]
Discovered an interesting interaction between BA and Kaoses Tweaks:

If you load Better Attributes after Kaoses Tweaks: Some things in Kaoses like Learning Rate limits etc. from the "XP" module in that mod, do not apply at all. (I guess you're using a similar method for handling XP?)
It's harder to test the other way around, but I'd wager the same applies that yours won't work if Kaoses is loaded last.
It's not a big deal on the pure XP gain side of things, as that's more elegantly handled via the attribute bonus from BA - but things like Learning Rate, Learning Limit etc. are nice to tweak via Kaoses.

Additionally, if Kaoses is loaded after Better Attributes, the focus points/level and attributes/levels in Better Attributes aren't working even when that module in Kaoses is switched off entirely. You have to set it via Kaoses to get it to work in that case.
(Not really a problem as you can just switch it on in Kaoses instead)

This may be a case of "can't fix" or "won't fix" but I figured it's still useful to know as you may wish to highlight something in the mod description to avoid endless support requests once this update is on Nexus Mods.

**Comment by Shadow32055** [comment]
Thanks for the information, this is expected when using custom models (why Harmony is preferred if possible). Only one can be loaded at a time and which ever one loads last will be used. Perhaps things like learning limits can be integrated as an additional bonus in the future.

**Comment by EvilTactician** [comment]
I think Kaoses has a bug anyway, as Learning Limit works now that I disabled it in Kaoses. (With the exact settings I had prior to Disabling it...)

I think it's one for you to ignore for now ;-)
