### ISSUE TITLE
XP for Assigned Party Roles

### ISSUE THREAD

**Issue by EvilTactician** [Shadow32055/Bannerlord.BetterAttributes#5]
**Feature Request**

The short version: Basically what this mod used to do:
https://www.nexusmods.com/mountandblade2bannerlord/mods/3279?tab=description

**Description**
When assigning party roles such as Scout, Quartermaster, Surgeon and Engineer - the Party Leader stops gaining XP in those, which leads to inconvenient min-max juggling of those roles to get anywhere in the game and pick up a few perks. My intention is to give the Party Leader a percentage of the XP those roles are earning so you still get some minor progress in those skills.

This could tie in nicely with this mod and be a fairly unique bonus to Intelligence, further setting it apart from other Attribute mods.

Suggested default setting is about 20-25% at 10 Int  (2 - 2.5% per attribute), making it user configurable like everything else in BA would give the user total freedom.

**Comment by Shadow32055** [comment]
Done and pushed to main as part of [https://github.com/Shadow32055/Bannerlord.BetterAttributes/commit/27801de952daee6b9824e3a4df759ceead98444b](url)
