### ISSUE TITLE
Companion Limit Bonus

### ISSUE THREAD

**Issue by EvilTactician** [Shadow32055/Bannerlord.BetterAttributes#6]
**Feature Request / Suggestion**

Default Configuration:
+1 Companion Limit per Social Attribute.

There's a lot of mods with tackle companion limits, so probably only worth it if it can be done in a compatible way.
Distinguished Service is probably one of the biggest ones which touches this (and is rather popular)

**Comment by Shadow32055** [comment]
Done and pushed.
